name = "jiwonz/luau_polyfill"
version = "0.1.0"
description = "A set of utilities to mimic common JS polyfills needed for translating projects from JS to Luau. Uploaded for pesde"
authors = [
	"jiwonz <me@jiwonz.kr>",
	"Imaduddin Haetami",
	"Chris Trześniewski <k.trzesniewski@gmail.com>",
    "Kyle Mitofsky <kylemit@gmail.com>",
    "Matt Hargett <plaztiksyke@gmail.com>",
    "Olivier Trepanier <otrepanier@roblox.com>",
    "Paul Doyle <pdoyle@roblox.com>",
    "Raymond Ng <rng@roblox.com>",
    "Zack Ovits <zack@boatbomber.com>",
]
repository = "https://github.com/jiwonz/luau-polyfill"
license = "MIT"
includes = [
	"src/**",
	"LICENSE",
	"pesde.toml",
	"README.md",
]
private = true

[target]
environment = "luau"
lib = "src/luau-polyfill/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
lune = "^0.8.9"
pesde = "^0.6.0"

[dev_dependencies]
multitarget = { name = "jiwonz/multitarget", version = "^0.4.0-rc.29", target = "lune" }
darklua = { name = "pesde/darklua", version = "^0.16.0", target = "lune" }
frktest = { name = "itsfrank/frktest", version = "^0.0.2", target = "lune" }

[dependencies]
task = { name = "jiwonz/task", version = "^0.2.0-rc.2" }
chalk_luau = { name = "kimpure/chalk_luau", version = "^0.1.7" }
