std = "luau"

[config.empty_if]
comments_count = true

[config.global_usage]
ignore_pattern = "LUA_ENV|__DEV__"

[config.shadowing]
ignore_pattern = "result|ok|^_"

[config.unused_variable]
ignore_pattern = "result|ok|^_"
